CREATE TABLE Pedido(
    id              INT GENERATED BY DEFAULT AS IDENTITY,
    nome_Produto    VARCHAR(200) NOT NULL,
    valor_Negociado DECIMAL(18, 2),
    data_da_Entrega DATE,
    url_Produto     TEXT         NOT NULL,
    url_Imagem      TEXT         NOT NULL,
    descricao       TEXT,
    status          VARCHAR(30)  NOT NULL,
    CONSTRAINT id_Pedido_pk PRIMARY KEY (id)
);