CREATE TABLE Pedido(
    id             INT GENERATED BY DEFAULT AS IDENTITY,
    nomeProduto    VARCHAR(200) NOT NULL,
    valorNegociado DECIMAL(18,2),
    dataDaEntrega  DATE,
    urlProduto     TEXT         NOT NULL,
    urlImagem      TEXT         NOT NULL,
    descricao      TEXT,
    status         VARCHAR(30) NOT NULL,
    CONSTRAINT id_Pedido_pk PRIMARY KEY (id)
);